### ISSUE TITLE
Implement rvalue constructors, rvalue assignment and the move function for all container classes

### ISSUE THREAD

**Issue by jmeintrup** [thm-mni-ii/sea#88]
To avoid unnecessary copy operations those functions should be implemented for all container classes

**Comment by shsr04** [comment]
Normally the compiler optimizes uses copy elision where possible. 
The move constructor +assignment are implicitly defined if you define no special members at all, so it should work out like it is.

Did you have a specific line in mind where an unnecessary copy happens?

**Comment by jmeintrup** [comment]
Yes, there are a few cases where it would be safer to provide a manual implementation: 

1) class variables are pointers
2) constructors that currently take as param a bitset which then gets copied on assignment - provide a constructor that specifically takes a rvalue as well

**Comment by shsr04** [comment]
Instead of explicit overloads, we can use *perfect forwarding* to take care of all kinds of references.

```cpp
void f(X const &x) { doSomethingConst(x); }
void f(X &&x) { doSomethingNonConst(std::move(x)); }
```

turns into

```cpp
template<class U>
void f(U&& x) { doSomething(std::forward<U>(x)); }
```

If we want to move a value away, we call `f(std::move(myArg))`, if we want to keep using it, we call `f(myArg)`. 

For example:
```cpp
Bitset<uint8_t> b(100);
// ...
RankSelect r(std::move(b));  // `r` steals `b`
```
Here, the `RankSelect` constructor will choose the rvalue overload and `std::forward` the given Bitset into its members.

(implemented in branch `variant-bitset`)

---
https://en.cppreference.com/w/cpp/utility/forward
